### ISSUE TITLE
チャット画面のデザインの修正

### ISSUE THREAD

**Issue by techiro** [techiro/hi-diary#31]
# 概要

<img src="https://user-images.githubusercontent.com/35694946/127624211-b73e95c0-8ee8-4294-83e6-d1fa9243c567.jpeg" width="50%"/>
画像が荒かったり、デバイスによって見え方が変わるため
アイコンは基本的にSF Symbols version 2.1を使用してください

ダウンロードリンク
https://devimages-cdn.apple.com/design/resources/download/SF-Symbols-2.1.dmg

# 変更内容

- チャットの背景は、Rowに持たせずに、RowViewを描画する元のBackGroundを使用するのでいらないです！
- 画像をSFSymbolsのみを使う。適切な画像がない場合は代わりのモック画像を挿入してください！
- ユーザーアイコンとコンテンツの区切り線はいらないです！
- パブリックの場合は地球儀アイコン、クローズドな場合、鍵のアイコンに変更！

-できればダークモード化
  -　コンテンツのバックグラウンドをWhiteではなく、contents_backgroundColorを定義してダークモードならば黒、そのままだと白に変更

## SFSymbolsの使い方

```swift

Image(systemName: "heart")

```

# 影響範囲

- NoteRow
- NoteLisstView
# 動作要件

# 補足

**Comment by techiro** [comment]
@Kuboshiman それぞれの要望を小さいissueに切り出してもらっても良いです！ブランチも同様に

**Comment by techiro** [comment]
@Kuboshiman 
## SFSymbolのアイコン
publicは、 `globe`
closedは、 `lock.fill`
かなー

**Comment by Kuboshiman** [comment]
OK

**Comment by Kuboshiman** [comment]
チャットの背景は、Rowに持たせずに、RowViewを描画する元のBackGroundを使用するのでいらないです！
→これがイマイチ分からん

**Comment by techiro** [comment]
@Kuboshiman 
NoteRowに持たせてるbackground
.background(Color.Card_Background)を無効にして欲しい。

**Comment by Kuboshiman** [comment]
無効にした。
contents_backgroundColorを定義してダークモードならば黒、そのままだと白に変更
→これは、NoteRowで定義しても構わんの？

**Comment by techiro** [comment]
それはContent(ハートとかコメント)を囲っているViewの話やね

**Comment by Kuboshiman** [comment]
じゃあ、そこは定義します
